name: cheftory-ai-recipe-summary-server dev CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-docker-image:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -f ./docker/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-ai-recipe-summary-server:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-ai-recipe-summary-server:latest

  deploy:
    environment: dev
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH to EC2 and create folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p cheftory-ai-recipe-summary-server/docker

      - name: Create .env on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat <<EOF > /home/ubuntu/cheftory-ai-recipe-summary-server/.env
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            BEDROCK_MODEL_ID=${{ secrets.BEDROCK_MODEL_ID }}
            BEDROCK_INFERENCE_PROFILE_ARN=${{ secrets.BEDROCK_INFERENCE_PROFILE_ARN }}
            AWS_LAMBDA_FUNCTION_URL_SEOUL=${{ secrets.AWS_LAMBDA_FUNCTION_URL_SEOUL }}
            AWS_LAMBDA_FUNCTION_URL_TOKYO=${{ secrets.AWS_LAMBDA_FUNCTION_URL_TOKYO }}
            AWS_LAMBDA_FUNCTION_URL_OSAKA=${{ secrets.AWS_LAMBDA_FUNCTION_URL_OSAKA }}
            AWS_LAMBDA_FUNCTION_URL_SINGAPORE=${{ secrets.AWS_LAMBDA_FUNCTION_URL_SINGAPORE }}
            AWS_LAMBDA_FUNCTION_URL_OREGON=${{ secrets.AWS_LAMBDA_FUNCTION_URL_OREGON }}
            AWS_LAMBDA_FUNCTION_URL_VIRGINIA=${{ secrets.AWS_LAMBDA_FUNCTION_URL_VIRGINIA }}
            EOF

      - name: Copy docker-compose.prod.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker/docker-compose.dev.yml"
          target: "/home/ubuntu/cheftory-ai-recipe-summary-server/"
          strip_components: 0

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd cheftory-ai-recipe-summary-server/docker

            # Docker Hub 로그인
            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            # compose 내 이미지 이름 치환 (placeholder → 실제 레지스트리)
            sed -i "s|image: cheftory-ai-recipe-summary-server:latest|image: ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-ai-recipe-summary-server:latest|g" docker-compose.dev.yml

            # 기존 컨테이너 정리
            sudo docker-compose -f docker-compose.dev.yml stop || true
            sudo docker-compose -f docker-compose.dev.yml rm -f || true
            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/cheftory-ai-recipe-summary-server:latest || true

            # 새 이미지 pull 및 실행
            sudo docker-compose -f docker-compose.dev.yml pull
            sudo docker-compose -f docker-compose.dev.yml up -d
